create table if not exists customers
(
    id         bigint generated by default as identity primary key,
    full_name  text not null,
    email      text not null unique,
    birth_date date,
    is_active  boolean   default false,
    created_at timestamp default now()
    );

create table products
(
    id           bigint generated by default as identity primary key,
    name         text           not null unique,
    category     text           not null,
    price        numeric(10, 2) not null check (price > 0),
    stock_qty    integer        not null check ( stock_qty >= 0 ),
    is_available boolean        not null,
    created_at   timestamp      not null
);

create table orders
(
    id             bigint generated by default as identity primary key,
    customer_email text           not null,
    status         text           not null check (status in ('new', 'paid', 'shipped', 'cancelled')),
    total_amount   numeric(12, 2) not null check (total_amount > 0),
    created_at     timestamp      not null
);

create table payments
(
    id             bigint generated by default as identity primary key,
    customer_email text           not null,
    method         text           not null check (method in ('card', 'cash', 'sbp')),
    amount         numeric(12, 2) not null check (amount > 0),
    paid_at        timestamp      not null
);

insert into customers (full_name, email, birth_date, is_active, created_at)
values ('Ivan Petrov', 'ivan.petrov@example.com', '1997-03-14', true, '2026-01-10 10:00:00'),
       ('Maria Smirnova', 'maria.smirnova@example.com', '1999-11-02', true, '2026-01-11 12:30:00'),
       ('Alexey Sidorov', 'alexey.sidorov@example.com', '1990-06-21', false, '2026-01-12 09:15:00'),
       ('Olga Ivanova', 'olga.ivanova@example.com', '2001-01-05', true, '2026-01-13 18:40:00'),
       ('Pavel Orlov', 'pavel.orlov@example.com', null, true, '2026-01-14 08:05:00');

insert into products (name, category, price, stock_qty, is_available, created_at)
values ('Milk 1L', 'dairy', 1.49, 120, true, '2026-01-05 10:00:00'),
       ('Bread', 'bakery', 0.99, 60, true, '2026-01-05 10:05:00'),
       ('Cheese', 'dairy', 3.79, 30, true, '2026-01-06 11:00:00'),
       ('Apples 1kg', 'fruit', 2.20, 80, true, '2026-01-06 12:00:00'),
       ('Coffee 250g', 'grocery', 6.50, 25, true, '2026-01-07 09:00:00'),
       ('Chocolate', 'grocery', 1.90, 0, false, '2026-01-08 09:00:00');

insert into orders (customer_email, status, total_amount, created_at)
values ('ivan.petrov@example.com', 'new', 12.40, '2026-01-10 10:10:00'),
       ('maria.smirnova@example.com', 'paid', 22.10, '2026-01-11 13:00:00'),
       ('olga.ivanova@example.com', 'shipped', 7.50, '2026-01-13 19:00:00'),
       ('pavel.orlov@example.com', 'paid', 15.99, '2026-01-14 09:00:00'),
       ('ivan.petrov@example.com', 'cancelled', 9.90, '2026-01-15 11:00:00');

insert into payments (customer_email, method, amount, paid_at)
values ('maria.smirnova@example.com', 'card', 22.10, '2026-01-11 13:02:00'),
       ('pavel.orlov@example.com', 'sbp', 15.99, '2026-01-14 09:05:00'),
       ('ivan.petrov@example.com', 'cash', 12.40, '2026-01-10 10:15:00'),
       ('olga.ivanova@example.com', 'card', 7.50, '2026-01-13 19:05:00'),
       ('ivan.petrov@example.com', 'card', 3.30, '2026-01-15 11:05:00');

/*-- number 1
insert into customers (full_name, email, birth_date, is_active)
VALUES ('Nikita Barkovskyi', 'worker@example', '2006-04-29', true);

-- number 2
update customers
set is_active = false
where id = 2
returning id, full_name;

-- number 3
update customers
set full_name = 'Gareth Bale'
where email = 'pavel.orlov@example.com'
returning id, full_name;

-- number 4
delete
from customers
where email = 'pavel.orlov@example.com'
returning *;

-- number 5
select count(*)
from customers;

-- number 6
select count(customers.is_active), is_active
from customers
group by is_active;

--number 7
select min(customers.created_at)
from customers;

select max(customers.created_at)
from customers;

-- number 8
select count(id)
from customers
where birth_date is null;

-- number 9
insert into customers (full_name, email, birth_date, is_active, created_at)
values ('Gareth Bale', 'worker@example', '1983-03-28', true)

-- number 10
insert into customers (full_name, email, birth_date)
values (null, null, null);
*/

/*-- number 1
insert into products (name, category, price, stock_qty, is_available, created_at)
values ('Макасины', 'Вещь', 2.09, 10, true, '2026-01-07 19:00:00');

-- number 2
update products
set stock_qty = stock_qty + 10
where name = 'Coffee 250g';

-- number 3
update products
set is_available = true and
                   stock_qty = 15
where name = 'Chocolate';

-- number 4
delete from products
where name = 'Макасины';

-- number 5
select count(*) from products;

-- number 6
select count(category), category
from products
group by category;

-- number 7
select avg(price), category
from products
group by category;

-- number 8
select min(price), max(price)
from products;

-- number 9
select count(is_available)
from products
where is_available is null;*/

/*-- number 1
insert into orders (customer_email, status, total_amount, created_at)
values ('worker@example', 'new', 4.01, '2026-01-13 21:00:00');

-- number 2
update orders
set status = 'paid'
where status = 'new'
returning id, status;

-- number 3
update orders
set total_amount = 2.01
where id = 1
returning id, total_amount;

-- number 4
delete from orders
where status = 'cancelled'
returning id, status;

-- number 5
select count(*) from orders;

-- number 6
select count(*), status
from orders
group by status;

-- number 7
select count(*), orders.customer_email
from orders
group by customer_email;

-- number 8
select avg(orders.total_amount)
from orders;

-- number 9
select min(orders.total_amount), max(orders.total_amount)
from orders;*/

