package org.java.core.lesson6.practiceDB.repository;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import org.java.core.lesson6.practiceDB.config.Config;
import org.java.core.lesson6.practiceDB.config.DbManager;
import org.java.core.lesson6.practiceDB.config.TxManager;
import org.java.core.lesson6.practiceDB.entity.User;

import java.sql.SQLException;

@NoArgsConstructor
@AllArgsConstructor
public class UserRepository {

    private Config config;
    private TxManager txManager;

    public void addUser(
            String name,
            int age
    ) {
        txManager
                .inTx(connection -> {
                    try (var pstm = connection.prepareStatement(
                            """
                                    insert into users (name, age) values (?, ?)
                                    """)
                    ) {
                        pstm.setString(1, name);
                        pstm.setInt(2, age);
                        pstm.execute();
                    } catch (SQLException e) {
                        System.out.println("Ошибка при добавлени пользователя в бд...");
                        e.printStackTrace();
                    }
                });
    }

    public void init() {
        try (var con = DbManager.getConnection(config)) {
            con.prepareStatement("""
                            create table if not exists users (
                                id bigint generated by default as identity primary key,
                                name varchar(255) not null,
                                age int not null check ( age > 0)
                            )
                            """)
                    .execute();
        } catch (SQLException e) {
            System.out.println("Произошла ошибка при выполнение запроса создания таблицы... ");
            e.printStackTrace();
        }
    }

    public User getUserById(long id) {
        try (var con = DbManager.getConnection(config)) {
            var pstm = con.prepareStatement("""
                    select * from users where id = ?;
                    """);
            pstm.setLong(1, id);
            var rs = pstm.executeQuery();

            boolean isUserExist = rs.next();

            if (!isUserExist) throw new RuntimeException("User with id " + id + " does not exist");

            return User.
                    builder()
                    .id(rs.getLong("id"))
                    .name(rs.getString("name"))
                    .age(rs.getInt("age"))
                    .build();


        } catch (SQLException e) {
            System.out.println("Произошла ошибка при выполнение запроса поиск пользователя по id: " + id);
            e.printStackTrace();
        }
        return null;
    }
}
